---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: front-out-policy
  namespace: front-end
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
      ports:
        - protocol: UDP
          port: 53
    - to:
      - namespaceSelector:
          matchLabels:
            tier: back
      ports:
        - protocol: TCP
          port: 9000

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: back-out-policy
  namespace: back-end
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
      ports:
        - protocol: UDP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-out-policy
  namespace: back-end
spec:
  podSelector:
    matchLabels:
      run: dbsvc
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 172.16.216.154/32
      ports:
        - protocol: TCP
          port: 3306

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ext-out-policy
  namespace: back-end
spec:
  podSelector:
    matchLabels:
      run: extsvc
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 172.217.0.0/16
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443